### ISSUE TITLE
Cursor and launcher issues.

### ISSUE THREAD

**Issue by spector700** [LovingMelody/nix-citizen#41] opened 2024-09-24 17:55 UTC
Hello,

I am on hyprland NVIDIA 560 drivers. I tried your flake on the 560 drivers but the launcher always freezes.

Then I tried the flake on nix-gaming and that works, but the cursor in game jumps around and is unusable in the inventory.
It seems the fix for this is to switch to wine version 9.13 (or newer, perhaps).

I don't know what wine versions the flakes use, but if yours is newer, do you know how to fix the launcher freezing?
Or if it's better to use the nix-gaming one then to fix the wine version?

**Comment by LovingMelody** [comment] 2024-09-24 20:22
I think the standard wine version may be using wine-ge still. You can try the `star-citizen-umu` package which is the version I personally use or you can override the wine version to something newer.

**Comment by spector700** [comment] 2024-09-24 21:06
Are you talking about nix-citizen or nix-gaming flake?

**Comment by LovingMelody** [comment] 2024-09-24 23:44
nix-citizen

**Comment by LovingMelody** [comment] 2024-09-25 19:09
Not able to reproduce that, are you using the same wine prefix from before?

**Comment by LovingMelody** [comment] 2024-09-25 23:16
Thanks for confirming I'll look into it, may just roll it back to the 1.x launcher

**Comment by spector700** [comment] 2024-09-26 00:18
Is there a way to see which wine version? And how can I change it, with perhaps an override? Or does umu not use wine or something (I don't know anything about umu)

**Comment by LovingMelody** [comment] 2024-09-26 02:23
umu uses proton, specifically whatever is the latest proton-ge in the targeted nixpkgs version. Standard star-citizen uses wine-ge. You can override it by overriding the attr wine.

**Comment by LovingMelody** [comment] 2024-09-27 01:35
Unable to recreate the issue that you had, launcher works fine for me on Hyprland with nvidia. I updated wine to the latest 9.18 instead of wine-ge and updated the launcher to be installed to 2.0.5. Can you see if any of these changes fixed the issue for you? (Only updated on nix-citizen pr not yet merged for nix-gaming)

**Comment by spector700** [comment] 2024-09-27 16:59
star-citizen-umu still freezes, But regular star-citizen now works.

I am installing again now, and I will see if the cursor also works.

**Comment by LovingMelody** [comment] 2024-09-27 17:07
Great, if not you will have to try the [lug-wiki entry](https://github.com/starcitizen-lug/knowledge-base/wiki/Troubleshooting#mousecursor-warp-issues-and-view-snapping-in-interaction-mode) for cursor issues. Hurricane took out my power & internet so I'm not able to do much until at least the internet is back.

**Comment by spector700** [comment] 2024-09-28 04:26
The cursor also works correctly now. Thanks for your help!

**Closed** 2024-09-30 08:31 UTC
